### ISSUE TITLE
Support aarch64-darwin

### ISSUE THREAD

**Issue by shinzui** [andreabedini/foliage#26]
I was trying to create a foliage package repository and following the instructions from [foliage-template](https://github.com/andreabedini/foliage-template), but I got an error while trying to create keys.

Running 

```
nix run github:andreabedini/foliage create-keys
```

returns

```
error: cannot find flake attribute 'github:andreabedini/foliage#defaultApp.aarch64-darwin'
```

I quickly looked at the flake, and I don't see why it's not working since you're already using `flake-utils.lib.eachDefaultSystem` which includes `aarch64-darwin`.

**Comment by andreabedini** [comment]
Hi @shinzui,

I realised this is because the musl64 toolchain that I use to produce a static executable only works on linux. I will address this.

**Comment by shinzui** [comment]
Thank you.

**Comment by andreabedini** [comment]
This should have been fixed in #27, let me know if it works for you.

**Comment by shinzui** [comment]
It's still failing for me, but it's going further before failing now. 

Here is the [verbose output](https://gist.github.com/shinzui/bb256c0a45e0d8f6103ea6787756fc9d) just in case it's helpful.

**Comment by andreabedini** [comment]
I am thinking that the problem could simply be that indeed I don't define `defaultApp.aarch64-darwin`. From the manual I read

    If no flake output attribute is given, nix run tries the following flake output attributes:
      · apps.<system>.default
      · packages.<system>.default

and therefore I only defined `package.<system>.default`. Perhaps try `nix run github:andreabedini/foliage#foliage` ? What version of nix are you using?
